import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";
import AppBar from "../components/AppBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppBar />
        <header className="appbar">
          <div
            className="container"
            style={{ marginTop: "-15px", marginBottom: "-45px" }}
          >
            <Link href="/" className="logo">
              Expense Tracker
            </Link>
            <nav className="nav">
              <Link href="/dashboard" className="btn btn-ghost">
                Dashboard
              </Link>
            </nav>
          </div>
        </header>

        <main>{children}</main>
      </body>
    </html>
  );
}
